AllCops:
  Exclude:
    - bin/yarn
    - db/schema.rb
    - lib/protobufs/traitify/**/*


inherit_from:
  - ./rubocop-airbnb.yml
  - ./rubocop-layout.yml
  - ./rubocop-lint.yml
  - ./rubocop-rails.yml
  - ./rubocop-style.yml

# TODO: Remove. Move to specific rules that need it
inherit_mode:
  merge:
    - Exclude
